# permissions to do viewer stewards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: steward-viewer-role
rules:
- apiGroups:
  - oam.crd.fp.net
  resources:
  - stewards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oam.crd.fp.net
  resources:
  - stewards/status
  verbs:
  - get
