---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stewards.oam.fp.net #should be start with Kind(s)
spec:
  group: oam.fp.net
  scope: Namespaced
  names:
    kind: Steward
    listKind: StewardList
    shortNames:
    - sw
    plural: stewards
    singular: steward
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
    - name: v1alpha2
      served: false
      storage: false
    - name: v1alpha1
      served: false
      storage: false
  additionalPrinterColumns:
  - name: Service
    type: string
    description: The apex service of this split.
    JSONPath: .spec.service